"""add num_array

Revision ID: 02921ccb2f73
Revises: 918cc38c0fa0
Create Date: 2022-05-22 01:15:47.590080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02921ccb2f73'
down_revision = '918cc38c0fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_pool', sa.Column('num_array', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_pool', 'num_array')
    # ### end Alembic commands ###
