"""empty message

Revision ID: 1cb3a481e3ef
Revises: f9cc93c9ac44
Create Date: 2022-05-20 12:32:50.087416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb3a481e3ef'
down_revision = 'f9cc93c9ac44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('adminkey_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'adminkey_hash')
    # ### end Alembic commands ###
