"""remove adminkey_hash

Revision ID: 918cc38c0fa0
Revises: cb87457baa4e
Create Date: 2022-05-22 00:16:06.753279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918cc38c0fa0'
down_revision = 'cb87457baa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('adminkey', sa.String(length=128), nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user', 'adminkey_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('adminkey_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'adminkey')
    # ### end Alembic commands ###
