"""rank table

Revision ID: caee1132c430
Revises: bf0da06a8e47
Create Date: 2022-05-07 18:15:50.852798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caee1132c430'
down_revision = 'bf0da06a8e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('moves', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_moves'), 'rank', ['moves'], unique=False)
    op.create_index(op.f('ix_rank_time'), 'rank', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rank_time'), table_name='rank')
    op.drop_index(op.f('ix_rank_moves'), table_name='rank')
    op.drop_table('rank')
    # ### end Alembic commands ###
