"""modify numbase_array

Revision ID: d6c781a9ad74
Revises: 02921ccb2f73
Create Date: 2022-05-22 01:50:20.654935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c781a9ad74'
down_revision = '02921ccb2f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_pool', sa.Column('numbase_array', sa.String(length=64), nullable=True))
    op.drop_column('game_pool', 'num_array')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_pool', sa.Column('num_array', sa.BLOB(), nullable=True))
    op.drop_column('game_pool', 'numbase_array')
    # ### end Alembic commands ###
