"""empty message

Revision ID: f9cc93c9ac44
Revises: caee1132c430
Create Date: 2022-05-18 22:35:37.890734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cc93c9ac44'
down_revision = 'caee1132c430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank', sa.Column('seconds', sa.Integer(), nullable=True))
    op.add_column('rank', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_index('ix_rank_time', table_name='rank')
    op.create_index(op.f('ix_rank_seconds'), 'rank', ['seconds'], unique=False)
    op.drop_column('rank', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank', sa.Column('time', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_rank_seconds'), table_name='rank')
    op.create_index('ix_rank_time', 'rank', ['time'], unique=False)
    op.drop_column('rank', 'timestamp')
    op.drop_column('rank', 'seconds')
    # ### end Alembic commands ###
